### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by machineghost** [dustingetz/react-chatview#12]
Your README says

> Please let me know if you use this,

and I'd love to do so ... if I could actually find some instructions on how to use it first :)

P.S. I know the README also says you're in alpha and that I have to read the source Luke, so just to be clear I understand that ... I'm just letting you know that I'd probably have chosen to use this library had their been documentation.  It's sort of a chicken and egg problem I guess.

**Comment by dustingetz** [comment]
Thanks for the ping and for the feedback. If enough people find this project valuable this we will definitely invest more time. (Guaging interest is why we ask for people to reach out and appreciate that you reached out, thanks!)

**Comment by machineghost** [comment]
NP.  Now if I could only find a documented React scroll tool that doesn't require me to know the exact dimensions of ... everything ... before I've even rendered ...

**Comment by dustingetz** [comment]
Have you seen the fiddle linked from the readme? https://jsfiddle.net/dustingetz/xvqzw747/

**Comment by machineghost** [comment]
I did see the fiddle, but ... look, I don't want to tell you what to do with your time or your project.  If I have to actually explain or convince you that a fiddle is not documentation, then it's already clear that you don't want to produce the kind of library I want to consume.

But if you want to write a library that people like would consume, you have a chicken and egg problem.  If you don't write docs, developers like me won't use your library, and if you're waiting for developers like me to use your library before writing docs then you never will.  There's no wrong/right answer, it's your time and your project, I'm just giving you an outsider's perspective.

**Comment by acomito** [comment]
Even just a very fast rundown of the required props (and a couple popular props) would be super helpful

**Comment by dustingetz** [comment]
```
let children = this.state.messages.map((v, ix) => <div key={ix}>{`${ix}: ${v}`}</div>);
<ReactChatView 
          className="content" // extra css class string
          flipped={true} // flipped means newest at bottom (chat), regular is newest at top (newsfeed)
          scrollLoadThreshold={50} // pixel distance from top that triggers an infinite load
          onInfiniteLoad={this.loadMoreHistory.bind(this)}> // callback to load more things, should cause more children to render
        {children} // the rows
      </ReactChatView>
```

**Comment by dustingetz** [comment]
props.onInfiniteLoad is the thing that is required, as well as children.

**Comment by dustingetz** [comment]
Added some documentation in #12
