### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'p.then') 

### ISSUE THREAD

**Issue by acomito** [dustingetz/react-chatview#13]
`react-chatview.js:88 TypeError: undefined is not an object (evaluating 'p.then')`

Ever seen this one? I'm getting it in safari.

**Comment by dustingetz** [comment]
https://github.com/dustingetz/react-chatview/blob/master/lib/react-chatview.js#L87-L88

Looks like onInfiniteLoad prop not defined - see the fiddle linked from the
readme for how to use that prop

**Comment by acomito** [comment]
Thanks for the quick response! I'll report back.
