### ISSUE TITLE
Online Demo?

### ISSUE THREAD

**Issue by winkler1** [dustingetz/react-chatview#2]
This looks great - nice tight code. Would love to add to react.rocks if that's possible (needs backend? or could have a fake data source?)

Thanks,
Jeff

**Comment by dustingetz** [comment]
The screenshot in the readme is clickable and leads to the online demo.

**Comment by dustingetz** [comment]
Let me know what you need from me to make this happen, thanks!

**Comment by winkler1** [comment]
Sweet! Never would have guessed that. A labeled link would be good :) 

All set, thanks a bunch!  The points about hardware acceleration are very interesting.

**Comment by winkler1** [comment]
http://react.rocks/example/react-chatview
