### ISSUE TITLE
Need maintainer

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-chatview#23]
Hello react-chatview contributors,

Would anyone like to take over maintenance? I regret that I have not had time to maintain this project for you guys. The problem is lack of automated tests. I am not using this library in any of my own projects and generally only work in javascript on behalf of a client, so it's difficult to merge changes since I can't thoroughly test them.

@maxnowack @adam187 @meticoeus @gimdongwoo @tonygentilcore @adam187 @khardenstine

**Comment by gimdongwoo** [comment]
I'm interested in the React.
I'm an open source developer and operate the React community in Korea.

I'm using react-chatview for production services and will be using it for newly services.
I already use React Chatview with ES6.

If you register me as a maintainer, I would like to contribute to this project.

Thank you.

**Comment by dustingetz** [comment]
OK! @gimdongwoo , I have granted push access to this repo.

**Comment by gimdongwoo** [comment]
Thank you.
First of all, do you mind if I merge postpone PRs?
The merge is required to improve functionality with fewer changes, or to change the specification of React.
I will add automated tests after that.

**Comment by dustingetz** [comment]
Do what you think is best!

**Comment by gimdongwoo** [comment]
There is no response from other contributors, so I will close the issue.

**Comment by dustingetz** [comment]
@gimdongwoo Thanks for your all your work on this. I am happy to transfer the repo to your name with a redirect. Let me know if/when you would like me to do that.

**Comment by gimdongwoo** [comment]
It is a pleasing and exciting proposal.

I would appreciate it if you transfer to the repository of our development community.
https://github.com/jsdevkr

This community covers some of the exciting open source JS technologies.
Approximately 600 JS developers are active.

I am using React Chatview in my product, so I would like to develop it further.
My product is hybrid mobile application using React.
[Android](https://play.google.com/store/apps/details?id=com.stylemirror.lime&hl=ko)
[iOS](https://itunes.apple.com/kr/app/%EC%B0%9C-zzimm-%ED%99%8D%EB%8C%80%EC%9E%85%EA%B5%AC-%ED%8C%A8%EC%85%98%EC%87%BC%ED%95%91-%ED%95%84%EC%88%98%EC%96%B4%ED%94%8C/id1122341113?mt=8).

Thank you.

**Comment by dustingetz** [comment]
OK! I just tried to transfer the repo. Github says: "You don’t have the permission to create repositories on jsdevkr" Please grant access and I will try again.

**Comment by gimdongwoo** [comment]
Sorry. I sent an invitation.
