### ISSUE TITLE
Need to npm publish

### ISSUE THREAD

**Issue by gimdongwoo** [dustingetz/react-chatview#25]
For eliminate the React Deprecated messages, I merged two of the less impacted and urgent PR.

[Test for React@latest]
https://jsfiddle.net/gimdongwoo/xo4fccbu/

I found npm package of react-chatview.
https://www.npmjs.com/package/react-chatview

I am not authorized to publish to NPM, so please publish.

**Comment by dustingetz** [comment]
Just added you to the npm package, see https://www.npmjs.com/package/react-chatview

**Comment by gimdongwoo** [comment]
Thank you. NPM Publish succeeded.
