### ISSUE TITLE
What does this line do?

### ISSUE THREAD

**Issue by zwhitchcox** [dustingetz/react-chatview#3]
https://github.com/dustingetz/react-chatview/blob/master/src/react-chatview.js#L25

I'm just a little confused as to how this is necessary. It says so `componentWillUnmount` can cancel outstanding `raf`s, but I don't see how this would be relevant. If the component has mounted, `this.rafRequestId` will already be assigned per `componentDidMount`.

I guess I just don't see how this is necessary, but I feel like you had a reason for doing it.

**Comment by dustingetz** [comment]
When <react-chatview /> is unmounted (say the page of the application changes) it needs to cancel any outstanding raf request, otherwise pollScroll will be called with a this pointer to a component that is no longer mounted
