### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by rzmz** [dustingetz/react-chatview#4]
I get the following error in my terminal when starting app with webpack:

Module parse failed: .../node_modules/react-chatview/src/react-chatview.js Line 1: Unexpected token:
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import ReactDOM from 'react-dom';
| import clone from 'lodash.clone';

How to solve this?

**Comment by dustingetz** [comment]
Which app? The messages demo?

**Comment by rzmz** [comment]
No I wanted to try your component in my app, I added it with 
npm i --save react-chatview 
and imported it in my project 
import ChatView from 'react-chatview' 
and then Webpack gives me this error.

**Comment by dustingetz** [comment]
For now you'll need some sort of webpack loader in your app webpack config to process react-chatview javascripts through babel, since react-chatview uses es6. Here is one way: `{ test: /node_modules\/react-chatview/, loader: 'babel' }`.

**Comment by rzmz** [comment]
Thanks! That works.
