### ISSUE TITLE
need a react component for easy to use

### ISSUE THREAD

**Issue by duminhtam** [dustingetz/react-chatview#7]
Hi can you create a example of react component to use your lib? It's hard to implement!

**Comment by dustingetz** [comment]
Here you go: https://jsfiddle.net/dustingetz/n9kfc17x/

This is linked from the readme now as well

**Comment by dustingetz** [comment]
Im sorry, i messed up, that fiddle isn't helpful

**Comment by dustingetz** [comment]
Here is the fiddle you want: https://jsfiddle.net/dustingetz/xvqzw747/ which is linked from the readme, is this sufficient or are you looking for something more?

**Comment by dustingetz** [comment]
@duminhtam Did this answer your question, can I close this issue?

**Comment by duminhtam** [comment]
I have to try many way and I can use already, thanks for your help :+1:
