### ISSUE TITLE
just saying hello

### ISSUE THREAD

**Issue by engenb** [dustingetz/react-chatview#9]
Hey!  Just wanted to drop a line and let you know that my team is using this in our chat project and we're happy with it!

We did end up forking it to change the webpack config a bit to suit our needs.  We were having some trouble with how you are aliasing react.  Feel free to [take a look](https://github.com/RedArrowLabsDeveloper/react-chatview) and reach out if you want to collaborate on anything regarding this project.

**Comment by dustingetz** [comment]
Thank you for reaching out! Thats great to hear. As far as I can tell from the diffs, the only changes are switching to the min version. I will make that change and publish a new version, if you want.

**Comment by engenb** [comment]
up to you.  we also had some trouble with the aliases on react and react-dom.  With them aliased to React and ReactDOM respectively, our require wasn't able to resolve them

**Comment by dustingetz** [comment]
@engenb Latest version has a more expressive externals config, does it work in your configuration?

**Comment by dustingetz** [comment]
Latest also uses lib/react-chatview.js as main (not the min version though, is that what people do? Redux uses the unminified babel output in main

**Comment by engenb** [comment]
we've switched focus away from our web application and onto a mobile app.  when we revisit the web app (coming up soon) I will definitely take a look.  thanks for the update!
